bossa:
	ruby ../onomatosynthesizer.rb bossa.vpal 120 4 bossa.mid

dougie:
	ruby ../onomatosynthesizer.rb dougie.vpal 160 4 dougie.mid

klezmer:
	ruby ../onomatosynthesizer.rb klezmer.vpal 160 4 klezmer.mid

latin:
	ruby ../onomatosynthesizer.rb latin.vpal 180 4 latin.mid

macarena:
	ruby ../onomatosynthesizer.rb macarena.vpal 240 2 macarena.mid

reggaeton:
	ruby ../onomatosynthesizer.rb reggaeton.vpal 180 8 reggaeton.mid

rock:
	ruby ../onomatosynthesizer.rb rock.vpal 180 4 rock.mid

tamborzao:
	ruby ../onomatosynthesizer.rb tamborzao.vpal 240 4 tamborzao.mid

all: bossa dougie klezmer latin macarena reggaeton rock tamborzao

clean:
	rm *.mid

